import { readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const migrationsDirectory = resolve(process.cwd(), "supabase/migrations");

function migration(): string {
  const files = readdirSync(migrationsDirectory)
    .filter((filename) => filename.endsWith("_performance_advisor_safe_remediations.sql"));

  expect(files).toHaveLength(1);
  return files.length === 1
    ? readFileSync(resolve(migrationsDirectory, files[0]), "utf8")
    : "";
}

describe("Supabase Performance Advisor safe remediations", () => {
  it("moves auth and current_setting calls behind scalar subqueries while retaining the effective Supabase roles", () => {
    const sql = migration();

    expect(sql).toMatch(/regexp_replace\([\s\S]*auth\\\./i);
    expect(sql).toMatch(/\(select auth\.\\1\(\)\)/i);
    expect(sql).toMatch(/current_setting/i);
    expect(sql).toMatch(/ALTER POLICY vouchers_public_read ON public\.vouchers\s+TO anon/i);
    expect(sql).toMatch(/ALTER POLICY vouchers_claim_owner_read ON public\.vouchers\s+TO authenticated/i);
  });

  it("keeps payment event uniqueness while removing only the exact duplicate index", () => {
    const sql = migration();

    expect(sql).toMatch(/DROP INDEX(?: CONCURRENTLY)? IF EXISTS public\.idx_payment_events_provider_event_unique/i);
    expect(sql).not.toMatch(/DROP (?:CONSTRAINT|INDEX)[^;]*payment_events_provider_provider_event_id_key/i);
  });

  it("adds a surrogate event key without changing the named-column event writer", () => {
    const sql = migration();

    expect(sql).toMatch(/ALTER TABLE public\.sponsored_discovery_events[\s\S]+ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY/i);
    expect(sql).toMatch(/ADD CONSTRAINT sponsored_discovery_events_pkey PRIMARY KEY \(id\)/i);
    expect(sql).not.toMatch(/(?:UPDATE|DELETE)\s+FROM\s+public\.sponsored_discovery_events/i);
  });

  it("preserves overlapping read and write predicates when consolidating policies", () => {
    const sql = migration();

    expect(sql).toMatch(/affiliate_own[\s\S]+app_private\.is_admin[\s\S]+DROP POLICY[\s\S]+affiliate_links_admin_read/i);
    expect(sql).toMatch(/outlet_offers_public_read[\s\S]+outlet_offers_manager_or_owner/i);
    expect(sql).toMatch(/user_roles_read_own_or_admin[\s\S]+user_roles_super_admin/i);
    expect(sql).toMatch(/vouchers_public_read[\s\S]+vouchers_claim_owner_read/i);
  });
});
