SET lock_timeout = '2s';

-- The index is redundant with the unique constraint's backing index.
DROP INDEX IF EXISTS public.idx_payment_events_provider_event_unique;

-- Add a surrogate key to this append-only event table. Its writer lists every
-- inserted column explicitly, so existing RPC parameters and result stay fixed.
ALTER TABLE public.sponsored_discovery_events
  ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.sponsored_discovery_events
  ADD CONSTRAINT sponsored_discovery_events_pkey PRIMARY KEY (id);

-- Merge public SELECT predicates while retaining the same PUBLIC role scope.
ALTER POLICY affiliate_own ON public.affiliate_links
  USING (
    ((SELECT auth.uid()) = user_id)
    OR app_private.is_admin((SELECT auth.uid()))
  );
DROP POLICY affiliate_links_admin_read ON public.affiliate_links;

ALTER POLICY recommendation_images_owner_read ON public.recommendation_images
  USING (
    (owner_id = (SELECT auth.uid()))
    OR app_private.can_review_recommendation((SELECT auth.uid()))
  );
DROP POLICY recommendation_images_admin_read ON public.recommendation_images;

-- Keep own/admin SELECT access and split the former ALL policy into the same
-- three write actions, avoiding overlap on SELECT.
ALTER POLICY user_roles_read_own_or_admin ON public.user_roles
  USING (
    ((SELECT auth.uid()) = user_id)
    OR app_private.is_admin((SELECT auth.uid()))
    OR app_private.is_super_admin((SELECT auth.uid()))
  );
DROP POLICY user_roles_super_admin_manages ON public.user_roles;
CREATE POLICY user_roles_super_admin_insert
  ON public.user_roles FOR INSERT TO PUBLIC
  WITH CHECK (app_private.is_super_admin((SELECT auth.uid())));
CREATE POLICY user_roles_super_admin_update
  ON public.user_roles FOR UPDATE TO PUBLIC
  USING (app_private.is_super_admin((SELECT auth.uid())))
  WITH CHECK (app_private.is_super_admin((SELECT auth.uid())));
CREATE POLICY user_roles_super_admin_delete
  ON public.user_roles FOR DELETE TO PUBLIC
  USING (app_private.is_super_admin((SELECT auth.uid())));

-- Preserve the public active-offer predicate and the managers' / owners'
-- existing visibility of offers outside that public predicate.
ALTER POLICY outlet_offers_public_read ON public.outlet_offers
  USING (
    (
      ((status)::text = 'active'::text)
      AND EXISTS (
        SELECT 1 FROM products p
        WHERE p.id = outlet_offers.product_id
          AND (p.status)::text = 'active'::text
          AND (p.review_status)::text = 'approved'::text
      )
      AND EXISTS (
        SELECT 1 FROM outlets o
        WHERE o.id = outlet_offers.outlet_id
          AND (o.status)::text = 'active'::text
      )
    )
    OR EXISTS (
      SELECT 1 FROM outlet_managers m
      WHERE m.outlet_id = outlet_offers.outlet_id
        AND m.user_id = (SELECT auth.uid())
    )
    OR EXISTS (
      SELECT 1 FROM outlets o
      JOIN vendors v ON v.id = o.vendor_id
      WHERE o.id = outlet_offers.outlet_id
        AND v.owner_id = (SELECT auth.uid())
    )
  );
DROP POLICY outlet_offers_outlet_manager ON public.outlet_offers;
DROP POLICY outlet_offers_vendor_owner ON public.outlet_offers;
CREATE POLICY outlet_offers_manager_or_owner_insert
  ON public.outlet_offers FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM outlet_managers m
      WHERE m.outlet_id = outlet_offers.outlet_id
        AND m.user_id = (SELECT auth.uid())
    )
    OR EXISTS (
      SELECT 1 FROM outlets o
      JOIN vendors v ON v.id = o.vendor_id
      WHERE o.id = outlet_offers.outlet_id
        AND v.owner_id = (SELECT auth.uid())
    )
  );
CREATE POLICY outlet_offers_manager_or_owner_update
  ON public.outlet_offers FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM outlet_managers m
      WHERE m.outlet_id = outlet_offers.outlet_id
        AND m.user_id = (SELECT auth.uid())
    )
    OR EXISTS (
      SELECT 1 FROM outlets o
      JOIN vendors v ON v.id = o.vendor_id
      WHERE o.id = outlet_offers.outlet_id
        AND v.owner_id = (SELECT auth.uid())
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM outlet_managers m
      WHERE m.outlet_id = outlet_offers.outlet_id
        AND m.user_id = (SELECT auth.uid())
    )
    OR EXISTS (
      SELECT 1 FROM outlets o
      JOIN vendors v ON v.id = o.vendor_id
      WHERE o.id = outlet_offers.outlet_id
        AND v.owner_id = (SELECT auth.uid())
    )
  );
CREATE POLICY outlet_offers_manager_or_owner_delete
  ON public.outlet_offers FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM outlet_managers m
      WHERE m.outlet_id = outlet_offers.outlet_id
        AND m.user_id = (SELECT auth.uid())
    )
    OR EXISTS (
      SELECT 1 FROM outlets o
      JOIN vendors v ON v.id = o.vendor_id
      WHERE o.id = outlet_offers.outlet_id
        AND v.owner_id = (SELECT auth.uid())
    )
  );

-- The former ALL policies only overlapped each table's public SELECT policy.
-- Split those policies by command while preserving their authenticated scope.
DROP POLICY place_accesses_admin_write ON public.place_accesses;
CREATE POLICY place_accesses_admin_insert ON public.place_accesses
  FOR INSERT TO authenticated
  WITH CHECK (app_private.is_admin((SELECT auth.uid())));
CREATE POLICY place_accesses_admin_update ON public.place_accesses
  FOR UPDATE TO authenticated
  USING (app_private.is_admin((SELECT auth.uid())))
  WITH CHECK (app_private.is_admin((SELECT auth.uid())));
CREATE POLICY place_accesses_admin_delete ON public.place_accesses
  FOR DELETE TO authenticated
  USING (app_private.is_admin((SELECT auth.uid())));

DROP POLICY place_informational_activities_admin_write ON public.place_informational_activities;
CREATE POLICY place_informational_activities_admin_insert ON public.place_informational_activities
  FOR INSERT TO authenticated
  WITH CHECK (app_private.is_admin((SELECT auth.uid())));
CREATE POLICY place_informational_activities_admin_update ON public.place_informational_activities
  FOR UPDATE TO authenticated
  USING (app_private.is_admin((SELECT auth.uid())))
  WITH CHECK (app_private.is_admin((SELECT auth.uid())));
CREATE POLICY place_informational_activities_admin_delete ON public.place_informational_activities
  FOR DELETE TO authenticated
  USING (app_private.is_admin((SELECT auth.uid())));

DROP POLICY places_admin_write ON public.places;
CREATE POLICY places_admin_insert ON public.places
  FOR INSERT TO authenticated
  WITH CHECK (app_private.is_admin((SELECT auth.uid())));
CREATE POLICY places_admin_update ON public.places
  FOR UPDATE TO authenticated
  USING (app_private.is_admin((SELECT auth.uid())))
  WITH CHECK (app_private.is_admin((SELECT auth.uid())));
CREATE POLICY places_admin_delete ON public.places
  FOR DELETE TO authenticated
  USING (app_private.is_admin((SELECT auth.uid())));

DROP POLICY product_places_admin_write ON public.product_places;
CREATE POLICY product_places_admin_insert ON public.product_places
  FOR INSERT TO authenticated
  WITH CHECK (app_private.is_admin((SELECT auth.uid())));
CREATE POLICY product_places_admin_update ON public.product_places
  FOR UPDATE TO authenticated
  USING (app_private.is_admin((SELECT auth.uid())))
  WITH CHECK (app_private.is_admin((SELECT auth.uid())));
CREATE POLICY product_places_admin_delete ON public.product_places
  FOR DELETE TO authenticated
  USING (app_private.is_admin((SELECT auth.uid())));

-- Separate anonymous public voucher reads from the authenticated owner-claim
-- path, then preserve both predicates in one policy per effective role.
ALTER POLICY vouchers_public_read ON public.vouchers
  TO anon;
ALTER POLICY vouchers_claim_owner_read ON public.vouchers
  TO authenticated
  USING (
    (
      ((review_status)::text = 'approved'::text)
      AND EXISTS (
        SELECT 1 FROM customer_voucher_claims claims
        WHERE claims.voucher_id = vouchers.id
          AND claims.user_id = (SELECT auth.uid())
      )
    )
    OR (
      is_active = true
      AND (review_status)::text = 'approved'::text
    )
  );

-- Normalize auth/current_setting expressions in place. ALTER POLICY leaves each
-- policy's command and role set unchanged; each original predicate remains.
DO $performance_advisor_initplan$
DECLARE
  p record;
  v_using text;
  v_check text;
  v_statement text;
BEGIN
  FOR p IN
    SELECT schemaname, tablename, policyname, qual, with_check
    FROM pg_policies
    WHERE schemaname = 'public'
      AND (
        coalesce(qual, '') ~* 'auth\.[a-z_]+\s*\('
        OR coalesce(with_check, '') ~* 'auth\.[a-z_]+\s*\('
        OR coalesce(qual, '') ~* 'current_setting\s*\('
        OR coalesce(with_check, '') ~* 'current_setting\s*\('
      )
  LOOP
    v_using := p.qual;
    v_check := p.with_check;

    IF v_using IS NOT NULL THEN
      v_using := regexp_replace(
        v_using,
        'auth\.([a-z_]+)\s*\(\s*\)',
        '(SELECT auth.\1())',
        'gi'
      );
      v_using := regexp_replace(
        v_using,
        'current_setting\s*\(([^()]*)\)',
        '(SELECT current_setting(\1))',
        'gi'
      );
    END IF;

    IF v_check IS NOT NULL THEN
      v_check := regexp_replace(
        v_check,
        'auth\.([a-z_]+)\s*\(\s*\)',
        '(SELECT auth.\1())',
        'gi'
      );
      v_check := regexp_replace(
        v_check,
        'current_setting\s*\(([^()]*)\)',
        '(SELECT current_setting(\1))',
        'gi'
      );
    END IF;

    v_statement := format(
      'ALTER POLICY %I ON %I.%I',
      p.policyname,
      p.schemaname,
      p.tablename
    );
    IF v_using IS NOT NULL THEN
      v_statement := v_statement || format(' USING (%s)', v_using);
    END IF;
    IF v_check IS NOT NULL THEN
      v_statement := v_statement || format(' WITH CHECK (%s)', v_check);
    END IF;

    EXECUTE v_statement;
  END LOOP;
END
$performance_advisor_initplan$;

RESET lock_timeout;
